name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: [ dev, main, prod ]

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for existing PR
        id: check_pr
        if: github.ref_name != 'prod'
        run: |
          EXISTING_PR=$(gh pr list --head ${{ github.ref_name }} --json number --jq ".[] | .number")
          echo "EXISTING_PR=$EXISTING_PR" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          if [[ -n $EXISTING_PR ]]; then                                                                                    
            echo "Pull request $EXISTING_PR exists. Skipping PR creation step"
          else
            echo "No existing pull requests. A PR will now be automatically created."
          fi
          echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"

      - name: Create PR to main
        if: github.ref_name == 'dev' && env.EXISTING_PR == ''
        run: |
          label="autodeploy: staging"
          gh label create "$label" -c=#201547 -f
          gh pr create \
          --base "main" \
          --head "dev" \
          --title "Deploy to staging" \
          --body "Automated pull request from dev to main. Merge to deploy to staging environment." \
          --label "$label" 

      - name: Create PR to prod
        if: github.ref_name == 'main' && env.EXISTING_PR == ''
        run: |
          label="autorelease: prepare"
          gh label create "$label"  -c=#201547 -f
          gh pr create \
          --base "prod" \
          --head "main" \
          --title "Prepare release" \
          --body "Automated pull request from main to prod. Merging this will trigger the creation/update of a release PR but deployment will not occur until the release PR is merged." \
          --label "$label"

      - name: Create release PR
        if: github.ref_name == 'prod'
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: prod
          package-name: action-test

      - name: Deploy
        # Deploy to test/stage on all pushes, but only deploy to prod when a tag is pushed
        if: contains(steps.check_pr.outputs.commit_message, 'chore')
        run: echo deploying to ${{ github.ref_name }}
