on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: main
          package-name: cast-in-channels
          changelog-types: '[{"type":"feat"},{"type":"fix"},{"type":"chore"}]'
